## Append samples you want in your CSV to this file as resources ##
resources:
- authorino-operator_v1beta1_authorino.yaml
- authorino-operator_v1beta2_authconfig.yaml
- authorino-operator_v1beta3_authconfig.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
